name: Push to S3

on: [push]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions
      - name: Setup AWS CLI
        uses: aws-actions
        with:
          aws-access-key-id: AKIAWABSAOR7PNNNDAW4
          aws-secret-access-key: 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
          aws-region: ap-south-1
      - name: Sync files to S3 bucket
        run: |
          aws s3 sync build s3://srilubuk --delete
